# author: Lei Wang

!obj:pylearn2.train.Train {
    dataset: &train !obj:imageTransformerDataset.TransformerDataset {
        raw : !obj:sar_ima_dataset.SarImaDataset {
            which_set: 'train',
            base_folder: '/home/lein/Work/sar_dnn/dataset/beaufort_gsl/',
            data_file_list: 'train.txt',
            preprocessor : !obj:preprocessing_standarize.Standardize {
              mean_std_file: '/home/lein/Work/sar_dnn/dataset/beaufort_gsl/mean_std_gsl_3conv.pkl'}, #it has to be full file path 
            fit_preprocessor: False,
        },
        transformer : !obj:transformer.TransformationPipeline { 
            input_space: !obj:pylearn2.space.Conv2DSpace {
                shape: [40, 40],
                num_channels: 2,
            },
            transformations: [
                !obj:transformer.Rotation {},
                !obj:transformer.Flipping {}
        ] },
        space_preserving : True,
    },
    model: !obj:pylearn2.monitor.push_monitor {
      model: !pkl: /home/lein/Work/sar_dnn/dataset/beaufort_gsl/gsl_conv_best_3conv.pkl,
      name: "monitor_stage_0"
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 128,
        learning_rate: .001,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .9
        },
        monitoring_dataset:
            {
                'train' : *train,
                'valid'  : !obj:sar_ima_dataset.SarImaDataset {
                              which_set: 'valid',
                              base_folder: '/home/lein/Work/sar_dnn/dataset/beaufort_gsl/',
                              data_file_list: 'valid.txt',
                              preprocessor : !obj:preprocessing_standarize.Standardize {
                                mean_std_file: '/home/lein/Work/sar_dnn/dataset/beaufort_gsl/mean_std_gsl_3conv.pkl'},
                              fit_preprocessor: False
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
              !obj:pylearn2.costs.cost.MethodCost {
              method: 'cost_from_X',
            },  !obj:pylearn2.costs.mlp.WeightDecay {
                coeffs: [0.0002, 0.0002, 0.0002, 0.0002, 0.0002],
            },
            ],
            },
        train_iteration_mode: 'even_shuffled_sequential',
        monitor_iteration_mode: 'even_shuffled_sequential',
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 500
        }
    },
    extensions:
        [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_objective',
             save_path: "/home/lein/Work/sar_dnn/dataset/beaufort_gsl/gsl_conv_best_3conv.pkl"
        }]
}
